In [14]:
import numpy as np

In [15]:
# You asked your 10 work friends to answer a survey. They gave you back the following dictionary object. 
# Removing "hipster points" category to make people categories and restuarent categoties equal
people = {'Wilke': {'willingness to travel': 1,
                  'desire for new experience': 1,
                  'cost': 1,
                  'indian food':1,
                  'mexican food':1,
                #  'hipster points':1,
                  'vegitarian': 1
                  },

          'Stroud': {'willingness to travel': 1,
                  'desire for new experience': 1,
                  'cost': 1,
                  'indian food':1,
                  'mexican food':1,
                #  'hipster points':1,
                  'vegitarian': 1
                  },

          'Kimbark': {'willingness to travel': 1,
                  'desire for new experience': 1,
                  'cost': 1,
                  'indian food':1,
                  'mexican food':1,
                #  'hipster points':1,
                  'vegitarian': 1
                  },

          'Adams': {'willingness to travel': 1,
                  'desire for new experience': 1,
                  'cost': 1,
                  'indian food':1,
                  'mexican food':1,
                #  'hipster points':1,
                  'vegitarian': 1
                  },

          'Milett': {'willingness to travel': 1,
                  'desire for new experience': 1,
                  'cost': 1,
                  'indian food':1,
                  'mexican food':1,
                #  'hipster points':1,
                  'vegitarian': 1
                  },

          'Cheng': {'willingness to travel': 1,
                  'desire for new experience': 1,
                  'cost': 1,
                  'indian food':1,
                  'mexican food':1,
                #  'hipster points':1,
                  'vegitarian': 1
                  },

          'Vasquez': {'willingness to travel': 1,
                  'desire for new experience': 1,
                  'cost': 1,
                  'indian food':1,
                  'mexican food':1,
                #  'hipster points':1,
                  'vegitarian': 1
                  },

          'Jiang': {'willingness to travel': 1,
                  'desire for new experience': 1,
                  'cost': 1,
                  'indian food':1,
                  'mexican food':1,
                #  'hipster points':1,
                  'vegitarian': 1
                  },

          'Ludlow': {'willingness to travel': 1,
                  'desire for new experience': 1,
                  'cost': 1,
                  'indian food':1,
                  'mexican food':1,
                #  'hipster points':1,
                  'vegitarian': 1
                  },
          
          'Fogelman': {'willingness to travel': 1,
                  'desire for new experience': 1,
                  'cost': 1,
                  'indian food':1,
                  'mexican food':1,
                #  'hipster points':1,
                  'vegitarian': 1
                  }

          }          

In [16]:
# Transform the user data into a matrix(M_people). Keep track of column and row ids.
peopleKeys, peopleValues = [], []
lastKey = 0
for k1, v1 in people.items():
    row = []  
    valueArray = np.array([np.random.dirichlet(np.ones(6),size=1)])
    idx = 0
    for k2 in v1.keys():
        peopleKeys.append(k1+'_'+k2)
        if k1 == lastKey:
            row.append(valueArray[0,0,idx])      
            lastKey = k1
        else:
            peopleValues.append(row)
            row.append(valueArray[0,0,idx])   
            lastKey = k1
        idx = idx + 1

In [17]:
M_people = np.array(peopleValues)
M_people.shape

(10, 6)

In [18]:
M_people

array([[0.19456689, 0.06318444, 0.1936516 , 0.29967164, 0.09480277,
        0.15412265],
       [0.28867341, 0.02191111, 0.05845968, 0.1345255 , 0.31877652,
        0.17765378],
       [0.08445659, 0.13814497, 0.19676897, 0.00151855, 0.08498664,
        0.49412428],
       [0.00211234, 0.10190791, 0.45128883, 0.10086466, 0.27611696,
        0.0677093 ],
       [0.02919676, 0.08390057, 0.5772272 , 0.17866299, 0.08035038,
        0.05066211],
       [0.03222971, 0.05194114, 0.07181115, 0.28856418, 0.10794258,
        0.44751123],
       [0.11513905, 0.03260828, 0.14034557, 0.13105953, 0.35218059,
        0.22866698],
       [0.60062263, 0.07416911, 0.08213205, 0.00660651, 0.07075146,
        0.16571825],
       [0.06437227, 0.07911242, 0.16718587, 0.06092421, 0.6086172 ,
        0.01978804],
       [0.3324584 , 0.19357228, 0.15988063, 0.04940525, 0.14998033,
        0.1147031 ]])

In [19]:
valueArrayFlacos = np.random.randint(5, size=6)+1
valueArrayAnamias = np.random.randint(5, size=6)+1
valueArrayChilis = np.random.randint(5, size=6)+1
valueArrayBlueFish = np.random.randint(5, size=6)+1
valueArrayCheesecakeFactory = np.random.randint(5, size=6)+1
valueArrayTacoBell = np.random.randint(5, size=6)+1
valueArrayBurgerKing = np.random.randint(5, size=6)+1
valueArrayPanchos = np.random.randint(5, size=6)+1
valueArrayMcDonalds = np.random.randint(5, size=6)+1
valueArrayWingStop = np.random.randint(5, size=6)+1

In [20]:
# Next you collected data from an internet website. You got the following information.
restaurants  = {'Flacos':{'distance' : valueArrayFlacos[0],
                        'novelty' : valueArrayFlacos[1],
                        'cost':  valueArrayFlacos[2],
                        'average rating': valueArrayFlacos[3],
                        'cuisine':valueArrayFlacos[4],
                        'vegitarians': valueArrayFlacos[5]
                        },

              'Anamias':{'distance' : valueArrayAnamias[0],
                        'novelty' : valueArrayAnamias[1],
                        'cost':  valueArrayAnamias[2],
                        'average rating': valueArrayAnamias[3],
                        'cuisine':valueArrayAnamias[4],
                        'vegitarians': valueArrayAnamias[5]
                        },

              'Chilis':{'distance' : valueArrayChilis[0],
                        'novelty' : valueArrayChilis[1],
                        'cost':  valueArrayChilis[2],
                        'average rating': valueArrayChilis[3],
                        'cuisine':valueArrayChilis[4],
                        'vegitarians': valueArrayChilis[5]
                        },

              'BlueFish':{'distance' : valueArrayBlueFish[0],
                        'novelty' : valueArrayBlueFish[1],
                        'cost':  valueArrayBlueFish[2],
                        'average rating': valueArrayBlueFish[3],
                        'cuisine':valueArrayBlueFish[4],
                        'vegitarians': valueArrayBlueFish[5]
                        },

              'CheesecakeFactory':{'distance' : valueArrayCheesecakeFactory[0],
                        'novelty' : valueArrayCheesecakeFactory[1],
                        'cost':  valueArrayCheesecakeFactory[2],
                        'average rating': valueArrayCheesecakeFactory[3],
                        'cuisine':valueArrayCheesecakeFactory[4],
                        'vegitarians': valueArrayCheesecakeFactory[5]
                        },

              'TacoBell':{'distance' : valueArrayTacoBell[0],
                        'novelty' : valueArrayTacoBell[1],
                        'cost':  valueArrayTacoBell[2],
                        'average rating': valueArrayTacoBell[3],
                        'cuisine':valueArrayTacoBell[4],
                        'vegitarians': valueArrayTacoBell[5]
                        },

              'BurgerKing':{'distance' : valueArrayBurgerKing[0],
                        'novelty' : valueArrayBurgerKing[1],
                        'cost':  valueArrayBurgerKing[2],
                        'average rating': valueArrayBurgerKing[3],
                        'cuisine':valueArrayBurgerKing[4],
                        'vegitarians': valueArrayBurgerKing[5]
                        },

              'Panchos':{'distance' : valueArrayPanchos[0],
                        'novelty' : valueArrayPanchos[1],
                        'cost':  valueArrayPanchos[2],
                        'average rating': valueArrayPanchos[3],
                        'cuisine':valueArrayPanchos[4],
                        'vegitarians': valueArrayPanchos[5]
                        },

              'McDonalds':{'distance' : valueArrayMcDonalds[0],
                        'novelty' : valueArrayMcDonalds[1],
                        'cost':  valueArrayMcDonalds[2],
                        'average rating': valueArrayMcDonalds[3],
                        'cuisine':valueArrayMcDonalds[4],
                        'vegitarians': valueArrayMcDonalds[5]
                        },

              'WingStop':{'distance' : valueArrayWingStop[0],
                        'novelty' : valueArrayWingStop[1],
                        'cost':  valueArrayWingStop[2],
                        'average rating': valueArrayWingStop[3],
                        'cuisine':valueArrayWingStop[4],
                        'vegitarians': valueArrayWingStop[5]
                        }

}

In [21]:
 # Transform the restaurant data into a matrix(M_resturants) use the same column index.
restaurantsKeys, restaurantsValues = [], []
for k1, v1 in restaurants.items():
    for k2, v2 in v1.items():
        restaurantsKeys.append(k1+'_'+k2)
        restaurantsValues.append(v2)

In [36]:
M_restaurants = np.reshape(restaurantsValues, (10,6))
M_restaurants
M_restaurants.shape

(10, 6)

In [23]:
# The most imporant idea in this project is the idea of a linear combination.  

# Informally describe what a linear combination is  and how it will relate to our resturant matrix.

print("In a linear combination we are multiplying each term by a constant and summing the results." + 
      "This relates to our restaurant matrix because multiplying our people matrix by the restaurant matrix will give us" + 
      "a 'restaurant score' for each person that we can use to optimize lunch choice.")

In a linear combination we are multiplying each term by a constant and summing the results.This relates to our restaurant matrix because multiplying our people matrix by the restaurant matrix will give usa 'restaurant score' for each person that we can use to optimize lunch choice.


In [24]:
# Choose a person and compute(using a linear combination) the top restaurant for them.  What does each entry in the resulting vector represent. 
#We will compute Janes scores for each restaurant.
flacoScore = M_people[0,0] * M_restaurants[0,0] + M_people[0,1] * M_restaurants[0,1] + M_people[0,2] * M_restaurants[0,2] + M_people[0,3] * M_restaurants[0,3]
anamiasScore = M_people[0,0] * M_restaurants[1,0] + M_people[0,1] * M_restaurants[1,1] + M_people[0,2] * M_restaurants[1,2] + M_people[0,3] * M_restaurants[1,3]
chilisScore = M_people[0,0] * M_restaurants[2,0] + M_people[0,1] * M_restaurants[2,1] + M_people[0,2] * M_restaurants[2,2] + M_people[0,3] * M_restaurants[2,3]
blueFishScore = M_people[0,0] * M_restaurants[3,0] + M_people[0,1] * M_restaurants[3,1] + M_people[0,2] * M_restaurants[3,2] + M_people[0,3] * M_restaurants[3,3]
cheesecakeFactoryScore = M_people[0,0] * M_restaurants[4,0] + M_people[0,1] * M_restaurants[4,1] + M_people[0,2] * M_restaurants[4,2] + M_people[0,3] * M_restaurants[4,3]
tacoBellScore = M_people[0,0] * M_restaurants[5,0] + M_people[0,1] * M_restaurants[5,1] + M_people[0,2] * M_restaurants[5,2] + M_people[0,3] * M_restaurants[5,3]
burgerKingScore = M_people[0,0] * M_restaurants[6,0] + M_people[0,1] * M_restaurants[6,1] + M_people[0,2] * M_restaurants[6,2] + M_people[0,3] * M_restaurants[6,3]
panchosScore = M_people[0,0] * M_restaurants[7,0] + M_people[0,1] * M_restaurants[7,1] + M_people[0,2] * M_restaurants[7,2] + M_people[0,3] * M_restaurants[7,3]
mcDonaldsScore = M_people[0,0] * M_restaurants[8,0] + M_people[0,1] * M_restaurants[8,1] + M_people[0,2] * M_restaurants[8,2] + M_people[0,3] * M_restaurants[8,3]
wingStopScore = M_people[0,0] * M_restaurants[9,0] + M_people[0,1] * M_restaurants[9,1] + M_people[0,2] * M_restaurants[9,2] + M_people[0,3] * M_restaurants[9,3]

In [25]:
janeScoreArray = np.array([flacoScore, anamiasScore, chilisScore, blueFishScore, cheesecakeFactoryScore, tacoBellScore, burgerKingScore, panchosScore, mcDonaldsScore, wingStopScore])
maxJaneScore = np.amax(janeScoreArray)
indexMaxJaneScore = np.where(janeScoreArray == maxJaneScore)
try:    
    print(f"Jane's max restaurant score is {maxJaneScore}, which is {list(restaurants.keys())[indexMaxJaneScore[0][0]]}.")
except:
    print("Crazy bizarro world where there were duplicate max scores for Jane. Re-run program.")


Jane's max restaurant score is 3.3293323472061065, which is Panchos.


In [26]:
# Next compute a new matrix (M_usr_x_rest  i.e. an user by restaurant) from all people.  What does the a_ij matrix represent? 
M_new_people = np.swapaxes(M_people, 0, 1)
M_usr_x_rest = np.matmul(M_restaurants, M_new_people)
print(M_usr_x_rest)
print("In M_usr_x_rest, the rows represent restaurants and the columns represent people.")

[[1.92058473 1.99785951 2.47207041 2.82824461 2.61751897 1.96284214
  2.31154415 1.69399259 2.80873142 2.31514188]
 [3.30524312 3.34715063 2.43658764 3.94348045 4.07877675 2.33683099
  3.25806855 3.43003259 3.8886727  3.3792215 ]
 [3.53022998 2.79398608 3.30718283 3.85260928 4.04396079 3.68836239
  3.23740309 2.04243801 3.3185146  2.98091891]
 [2.44588367 2.7282388  2.73983981 1.95920348 1.6992098  3.16777693
  2.76762022 2.2524933  2.4628192  2.07533888]
 [2.58573466 2.56862662 2.20700186 3.21500557 3.29724    1.88822451
  2.55195209 2.74408905 3.06668557 2.88106917]
 [2.10105869 2.42494546 1.89026626 2.1996974  1.73293977 2.40040849
  2.5799361  1.46535474 3.04660047 1.85702689]
 [2.23023127 2.00644546 2.05809396 2.07537631 2.44217301 1.94415713
  1.87069574 2.53783411 1.54382852 2.14878641]
 [3.98130585 3.51001515 3.47898304 3.73155004 4.31116053 3.38870332
  3.28984817 4.30136441 2.91542328 3.88410297]
 [2.14524452 1.79167984 3.09509527 2.06100513 2.15957822 2.85873246
  2.05523087

In [27]:
# Sum all columns in M_usr_x_rest to get optimal restaurant for all users.  What do the entry’s represent?
print(np.sum(M_usr_x_rest, axis=1))
print("The entries represent the total score for each restaurant.")

maxRestaurantScore = np.amax(np.sum(M_usr_x_rest, axis=1))
indexMaxRestaurantScore = np.where(np.sum(M_usr_x_rest, axis=1) == maxRestaurantScore)
try:    
    print(f"Max restaurant score is {maxRestaurantScore}, which is {list(restaurants.keys())[indexMaxRestaurantScore[0][0]]}.")
except:
    print("Crazy bizarro world where there were duplicate max scores for restaurants. Re-run program.")


[22.9285304  33.4040649  32.79560595 24.2984241  27.0056291  21.69823428
 20.85762192 36.79245677 21.63389043 26.07193639]
The entries represent the total score for each restaurant.
Max restaurant score is 36.792456768522975, which is Panchos.


In [28]:
# Now convert each row in the M_usr_x_rest into a ranking for each user and call it M_usr_x_rest_rank.   Do the same as above to generate the optimal resturant choice.  
sortedResults = M_usr_x_rest.argsort()[::-1]
sortedResults

maxRowIndex = np.argmax(sortedResults, axis=0)
print(maxRowIndex)

for i, optimalRestaurant in enumerate(maxRowIndex):
    print(f"Max restaurant score for {list(people.keys())[i]} is {list(restaurants.keys())[optimalRestaurant]}.")

[1 2 4 0 0 1 2 5 0 4]
Max restaurant score for Wilke is Anamias.
Max restaurant score for Stroud is Chilis.
Max restaurant score for Kimbark is CheesecakeFactory.
Max restaurant score for Adams is Flacos.
Max restaurant score for Milett is Flacos.
Max restaurant score for Cheng is Anamias.
Max restaurant score for Vasquez is Chilis.
Max restaurant score for Jiang is TacoBell.
Max restaurant score for Ludlow is Flacos.
Max restaurant score for Fogelman is CheesecakeFactory.


In [29]:
# Why is there a difference between the two?  What problem arrives?  What does represent in the real world?
print("There is a difference because there may be groups of people with similar optimal choices.",
      "This represents the real world situation where taking all people into account, the entire group cannot make an optimal choice", 
      "as each restaurant may be optimal for a sub group of people.")

There is a difference because there may be groups of people with similar optimal choices. This represents the real world situation where taking all people into account, the entire group cannot make an optimal choice as each restaurant may be optimal for a sub group of people.


In [30]:
# How should you preprocess your data to remove this problem. 
print("We should pre-process our data so we take groups of people into account.")

We should pre-process our data so we take groups of people into account.


In [31]:
# Find  user profiles that are problematic, explain why?
print(M_people)
print(people.keys())
print("People will very low scores for certain criteria could be problematic. Andy has a value of 0.007", 
      "for willingness to travel which could be problematic. Daniel has a value of 0.001 for desire for new experience",
      "which could be problematic. These low criteria scores could make it difficult for an optimal restaurant choice to be found for the group.")

[[0.19456689 0.06318444 0.1936516  0.29967164 0.09480277 0.15412265]
 [0.28867341 0.02191111 0.05845968 0.1345255  0.31877652 0.17765378]
 [0.08445659 0.13814497 0.19676897 0.00151855 0.08498664 0.49412428]
 [0.00211234 0.10190791 0.45128883 0.10086466 0.27611696 0.0677093 ]
 [0.02919676 0.08390057 0.5772272  0.17866299 0.08035038 0.05066211]
 [0.03222971 0.05194114 0.07181115 0.28856418 0.10794258 0.44751123]
 [0.11513905 0.03260828 0.14034557 0.13105953 0.35218059 0.22866698]
 [0.60062263 0.07416911 0.08213205 0.00660651 0.07075146 0.16571825]
 [0.06437227 0.07911242 0.16718587 0.06092421 0.6086172  0.01978804]
 [0.3324584  0.19357228 0.15988063 0.04940525 0.14998033 0.1147031 ]]
dict_keys(['Wilke', 'Stroud', 'Kimbark', 'Adams', 'Milett', 'Cheng', 'Vasquez', 'Jiang', 'Ludlow', 'Fogelman'])
People will very low scores for certain criteria could be problematic. Andy has a value of 0.007 for willingness to travel which could be problematic. Daniel has a value of 0.001 for desire for new

In [32]:
# Think of two metrics to compute the disatistifaction with the group.  
print("We could take the difference between the group’s optimal restaurant score, and each individual’s optimal restaurant score.",
      "The difference between these values could be considered a “dissatisfaction score” for each person.\n")
print("We could also look at highly ranked criteria for each person and determine if that was in alignment with the group's restaurant choice.",
      "For example, if cost > .75 for an individual, if the chosen restaurant is not highly ranked with cost we could consider that dissatisfaction.")

We could take the difference between the group’s optimal restaurant score, and each individual’s optimal restaurant score. The difference between these values could be considered a “dissatisfaction score” for each person.

We could also look at highly ranked criteria for each person and determine if that was in alignment with the group's restaurant choice. For example, if cost > .75 for an individual, if the chosen restaurant is not highly ranked with cost we could consider that dissatisfaction.


In [33]:
# Should you split in two groups today? 
print("Since the group's optimal restaurant choice of Cheesecake Factory is not in alignment with any individual's optimal restaurant choice, we should split into 2 groups.")

Since the group's optimal restaurant choice of Cheesecake Factory is not in alignment with any individual's optimal restaurant choice, we should split into 2 groups.


In [34]:
# Ok. Now you just found out the boss is paying for the meal. How should you adjust. Now what is best restaurant?
people = {'Wilke': {'willingness to travel': valueArrayJane[0,0,0],
                  'desire for new experience': valueArrayJane[0,0,1],
                  'cost': 0.0,
                  'indian food':valueArrayJane[0,0,3],
                  'mexican food':valueArrayJane[0,0,4],
                  #'hipster points':
                  'vegitarian': valueArrayJane[0,0,5]
                  },

          'Stroud': {'willingness to travel': valueArrayJack[0,0,0],
                  'desire for new experience': valueArrayJack[0,0,1],
                  'cost': 0.0,
                  'indian food':valueArrayJack[0,0,3],
                  'mexican food':valueArrayJack[0,0,4],
                  #'hipster points':
                  'vegitarian': valueArrayJack[0,0,5]
                  },

          'Kimbark': {'willingness to travel': valueArrayJill[0,0,0],
                  'desire for new experience': valueArrayJill[0,0,1],
                  'cost': 0.0,
                  'indian food':valueArrayJill[0,0,3],
                  'mexican food':valueArrayJill[0,0,4],
                  #'hipster points':
                  'vegitarian': valueArrayJill[0,0,5]
                  },

          'Adams': {'willingness to travel': valueArrayTim[0,0,0],
                  'desire for new experience': valueArrayTim[0,0,1],
                  'cost': 0.0,
                  'indian food':valueArrayTim[0,0,3],
                  'mexican food':valueArrayTim[0,0,4],
                  #'hipster points':
                  'vegitarian': valueArrayTim[0,0,5]
                  },

          'Milett': {'willingness to travel': valueArrayBob[0,0,0],
                  'desire for new experience': valueArrayBob[0,0,1],
                  'cost': 0.0,
                  'indian food':valueArrayBob[0,0,3],
                  'mexican food':valueArrayBob[0,0,4],
                  #'hipster points':
                  'vegitarian': valueArrayBob[0,0,5]
                  },

          'Cheng': {'willingness to travel': valueArrayAndy[0,0,0],
                  'desire for new experience': valueArrayAndy[0,0,1],
                  'cost': 0.0,
                  'indian food':valueArrayAndy[0,0,3],
                  'mexican food':valueArrayAndy[0,0,4],
                  #'hipster points':
                  'vegitarian': valueArrayAndy[0,0,5]
                  },

          'Vasquez': {'willingness to travel': valueArrayCharlie[0,0,0],
                  'desire for new experience': valueArrayCharlie[0,0,1],
                  'cost': 0.0,
                  'indian food':valueArrayCharlie[0,0,3],
                  'mexican food':valueArrayCharlie[0,0,4],
                  #'hipster points':
                  'vegitarian': valueArrayCharlie[0,0,5]
                  },

          'Jiang': {'willingness to travel': valueArrayPete[0,0,0],
                  'desire for new experience': valueArrayPete[0,0,1],
                  'cost': 0.0,
                  'indian food':valueArrayPete[0,0,3],
                  'mexican food':valueArrayPete[0,0,4],
                  #'hipster points':
                  'vegitarian': valueArrayPete[0,0,5]
                  },

          'Ludlow': {'willingness to travel': valueArrayDaniel[0,0,0],
                  'desire for new experience': valueArrayDaniel[0,0,1],
                  'cost': 0.0,
                  'indian food':valueArrayDaniel[0,0,3],
                  'mexican food':valueArrayDaniel[0,0,4],
                  #'hipster points':
                  'vegitarian': valueArrayDaniel[0,0,5]
                  },

          'Fogelman': {'willingness to travel': valueArrayBrad[0,0,0],
                  'desire for new experience': valueArrayBrad[0,0,1],
                  'cost': 0.0,
                  'indian food':valueArrayBrad[0,0,3],
                  'mexican food':valueArrayBrad[0,0,4],
                  #'hipster points':
                  'vegitarian': valueArrayBrad[0,0,5]
                  }
          }          

NameError: name 'valueArrayJane' is not defined

In [ ]:
peopleKeys, peopleValues = [], []
lastKey = 0
for k1, v1 in people.items():
    row = []
    
    for k2, v2 in v1.items():
        peopleKeys.append(k1+'_'+k2)
        if k1 == lastKey:
            row.append(v2)      
            lastKey = k1
        else:
            peopleValues.append(row)
            row.append(v2)   
            lastKey = k1

M_people = np.array(peopleValues)
M_new_people = np.swapaxes(M_people, 0, 1)
M_usr_x_rest = np.matmul(M_restaurants, M_new_people)

print(M_usr_x_rest)
print(np.sum(M_usr_x_rest, axis=1))

In [ ]:
maxRestaurantScore = np.amax(np.sum(M_usr_x_rest, axis=1))
indexMaxRestaurantScore = np.where(np.sum(M_usr_x_rest, axis=1) == maxRestaurantScore)
print("If the boss is paying, then cost consideration is no longer a factor. We should set this criteria to 0 for each person and re-run.")

try:    
    print(f"Max restaurant score when cost is 0 is {maxRestaurantScore}, which is {list(restaurants.keys())[indexMaxRestaurantScore[0][0]]}.")
except:
    print("Crazy bizarro world where there were duplicate max scores for restaurants. Re-run program.")

In [ ]:
# Tommorow you visit another team. You have the same restaurants and they told you their optimal ordering for restaurants.  Can you find their weight matrix? 
print("Yes, you could multiply the restaurant matrix by the transpose of the ordering matrix to find the weight matrix.")