In [606]:
import numpy as np

In [607]:
# You asked your 10 work friends to answer a survey. They gave you back the following dictionary object. 
# Removing "hipster points" category to make people categories and restuarent categoties equal

people = ['Wilke', 'Stroud', 'Kimbark', 'Adams', 'Milett', 'Cheng', 'Vasquez', 'Jiang', 'Ludlow', 'Fogelman']
people_cat = ['willingness to travel', 'desire for new experience', 'cost', 'indian food', 'mexican food', 'vegitarian']

In [608]:
# Transform the user data into a matrix(M_people). Keep track of column and row ids.
people_dict =  {}
M_people = []

for key in people: 
    cat_dict = {}
    valueArray = np.random.dirichlet(np.ones(len(people_cat)),size=1)
    idx = 0
    for cat_key in people_cat: 
        cat_dict[cat_key] = valueArray[0, idx] 
        idx += 1
    people_dict[key] = cat_dict
    M_people.append(valueArray[0])

In [609]:
M_people = np.array(M_people)
M_people.shape

(10, 6)

In [610]:
# Next you collected data from an internet website. You got the following information.
restaurants = ['Flacos', 'Chilis', 'TacoBell', 'BurgerKing', 'McDonalds', 'pizzaHut', 'Mayan', 'DairyQueen', 'MiSo', 'Mayuri']
restaurants_cat = ['distance', 'novelty', 'cost', 'average rating', 'cuisine', 'vegitarians']

In [611]:
# Transform the restaurant data into a matrix(M_resturants) use the same column index.
restaurants_dict =  {}
M_resturants = []

for key in restaurants: 
    cat_dict = {}
    valueArray = np.random.randint(5, size=6)+1
    idx = 0
    for cat_key in people_cat: 
        cat_dict[cat_key] = valueArray[idx] 
        idx += 1
    restaurants_dict[key] = cat_dict
    M_resturants.append(valueArray)

In [612]:
M_resturants = np.array(M_resturants)
M_restaurants = np.reshape(M_resturants, (10,6))
M_resturants.shape

(10, 6)

In [613]:
# The most imporant idea in this project is the idea of a linear combination.  

# Informally describe what a linear combination is  and how it will relate to our resturant matrix.

print("Linear combination is an expression where each term is constructed  by multiplying with a constant and summing the results." + 
      "In restaurant problem, we need to multiply people matrix by the restaurant matrix which will give us " + 
      "a 'restaurant score' for each person that we can use to identify the restaurant.")

Linear combination is an expression where each term is constructed  by multiplying with a constant and summing the results.In restaurant problem, we need to multiply people matrix by the restaurant matrix which will give us a 'restaurant score' for each person that we can use to identify the restaurant.


In [614]:
# Choose a person and compute(using a linear combination) the top restaurant for them.  
# What does each entry in the resulting vector represent. We will compute first person scores for each restaurant.
restaurants_score = []

for restaurant in M_restaurants:
    restaurant_score = np.sum([l*n for l, n in zip(M_people[0], restaurant)])
    restaurants_score.append(restaurant_score)

In [615]:
max_value = max(restaurants_score)
max_index = restaurants_score.index(max_value)

print(f"{people[0]}'s max restaurant score is {max_value}, which is {restaurants[max_index]}.")

Wilke's max restaurant score is 4.270401903130272, which is pizzaHut.


In [616]:
# Next compute a new matrix (M_usr_x_rest  i.e. an user by restaurant) from all people.  What does the a_ij matrix represent? 
M_people_new = np.swapaxes(M_people, 0, 1)
M_usr_x_rest = np.matmul(M_restaurants, M_people_new)
print("Matrix represents restaurants by people, the rows represent restaurants and the columns represent people.\n")
print(M_usr_x_rest)

Matrix represents restaurants by people, the rows represent restaurants and the columns represent people.

[[2.78722566 3.000913   3.26337546 2.70989493 3.14389652 3.22051469
  3.02211406 2.97987072 3.38470804 3.12241512]
 [3.20933771 3.02947379 2.15675062 1.66365013 2.66789652 2.58208491
  2.93429739 3.38469586 3.1388418  2.66249772]
 [3.33982578 3.13932882 3.02968474 2.4218493  2.83082958 2.29107323
  3.13317362 3.17883814 3.11547766 2.73011188]
 [3.40122732 2.82918193 3.13473348 2.89251205 3.15339778 4.03617397
  3.80150412 3.22266138 4.61862756 3.48730306]
 [2.25394793 2.07317543 2.27705924 2.19297386 2.42621051 3.09194521
  2.67653212 2.29735594 3.27139901 2.73381516]
 [4.2704019  3.87060616 2.72863113 3.6682446  3.42393098 3.74482888
  3.58165454 4.20271494 3.11651845 3.30570283]
 [3.03830516 3.66084093 3.21201352 3.18310624 3.59858044 4.02335449
  2.838291   3.66613302 2.88376589 3.20902116]
 [2.17903427 1.84977241 1.94879013 1.85699429 1.87216919 2.00088995
  2.2361912  1.98097

In [617]:
# Sum all columns in M_usr_x_rest to get optimal restaurant for all users.  What do the entry’s represent?

print("The entries represent the total score for each restaurant.\n")
print(np.sum(M_usr_x_rest, axis=1))

Final_Restaurant_Scores = list(np.sum(M_usr_x_rest, axis=1))
max_Restaurant_Score = max(Final_Restaurant_Scores)
max_Restaurant_Score_index = Final_Restaurant_Scores.index(max_Restaurant_Score)

print(f"\nMax restaurant score is {max_Restaurant_Score}, which is {restaurants[max_Restaurant_Score_index]}.")

The entries represent the total score for each restaurant.

[30.6349282  27.42952646 29.21019275 34.57732266 25.2944144  35.91323441
 33.31341185 20.33136828 32.46520554 39.52913304]

Max restaurant score is 39.52913303818918, which is Mayuri.


In [618]:
# Now convert each row in the M_usr_x_rest into a ranking for each user and call it M_usr_x_rest_rank.   
# Do the same as above to generate the optimal resturant choice.  
M_usr_x_rest = M_usr_x_rest.argsort()[::-1]
print(M_usr_x_rest, '\n')

maxRowIndex = np.argmax(M_usr_x_rest, axis=0)

for i, optimalRestaurant in enumerate(maxRowIndex):
    print(f"Max restaurant score for {people[i]} is {restaurants[optimalRestaurant]}.")

[[8 5 9 6 4 7 2 0 1 3]
 [8 6 2 5 7 0 9 4 1 3]
 [1 3 4 2 7 9 5 0 6 8]
 [6 8 0 3 9 2 4 1 7 5]
 [2 8 9 4 6 3 5 1 7 0]
 [1 3 0 2 7 4 6 9 5 8]
 [1 3 2 4 7 0 9 6 5 8]
 [5 3 9 4 2 8 6 1 7 0]
 [3 2 5 9 4 6 1 8 0 7]
 [3 0 7 1 6 9 4 5 2 8]] 

Max restaurant score for Wilke is Flacos.
Max restaurant score for Stroud is BurgerKing.
Max restaurant score for Kimbark is Flacos.
Max restaurant score for Adams is MiSo.
Max restaurant score for Milett is BurgerKing.
Max restaurant score for Cheng is TacoBell.
Max restaurant score for Vasquez is Chilis.
Max restaurant score for Jiang is pizzaHut.
Max restaurant score for Ludlow is BurgerKing.
Max restaurant score for Fogelman is TacoBell.


In [619]:
# Why is there a difference between the two?  What problem arrives?  What does represent in the real world?
print("There is a difference between the two because there may be groups of people with similar optimal choices.",
      "This scenario represents the real world situation where we might need to consider all people into account,"
      " the entire group cannot make an optimal choice as each restaurant may be optimal for a sub group of people.")

There is a difference between the two because there may be groups of people with similar optimal choices. This scenario represents the real world situation where we might need to consider all people into account, the entire group cannot make an optimal choice as each restaurant may be optimal for a sub group of people.


In [620]:
# How should you preprocess your data to remove this problem. 
print("We can pre-process the data to identify groups of people that might remove this issue.")

We can pre-process the data to identify groups of people that might remove this issue.


In [621]:
# Find  user profiles that are problematic, explain why?
print(M_people)
print('\n', people,)
print('\n', people_cat, '\n')
print("People with very low scores for certain criteria could be problematic.",  
      "Stroud, Adams and Jiang are problematic profiles because low scores", 
      "These low criteria scores could make it difficult for an optimal restaurant choice to be found for the group.")

[[0.41672465 0.21788529 0.27320477 0.03885103 0.02157939 0.03175487]
 [0.41828049 0.01959144 0.23372457 0.16981903 0.06481855 0.09376592]
 [0.05467236 0.25933809 0.1657491  0.31054795 0.11857661 0.09111589]
 [0.03348355 0.01814013 0.54051264 0.16114584 0.08926174 0.1574561 ]
 [0.22382327 0.0367901  0.22525409 0.16462091 0.2045297  0.14498192]
 [0.10406268 0.00905888 0.30485129 0.00816893 0.51719704 0.05666118]
 [0.20399007 0.28338849 0.18964409 0.04719729 0.16456086 0.1112192 ]
 [0.47870612 0.04891045 0.21842197 0.06793622 0.13035646 0.05566878]
 [0.0898252  0.42768527 0.01257636 0.00782794 0.38945645 0.07262878]
 [0.13491398 0.07125728 0.21910312 0.084562   0.25695625 0.23320738]]

 ['Wilke', 'Stroud', 'Kimbark', 'Adams', 'Milett', 'Cheng', 'Vasquez', 'Jiang', 'Ludlow', 'Fogelman']

 ['willingness to travel', 'desire for new experience', 'cost', 'indian food', 'mexican food', 'vegitarian'] 

People with very low scores for certain criteria could be problematic. Stroud, Adams and Jiang

In [622]:
# Think of two metrics to compute the disatistifaction with the group.  
print("The difference between groups max restaurant score and individual max restaurant score is a " 
      "measure of “dissatisfaction score” for each person.\n")

print("Any other scores like cost, if there is a lot of difference between group score and individual score"
      "can be considered as 'dissatisfaction score' for each person.\n")


The difference between groups max restaurant score and individual max restaurant score is a measure of “dissatisfaction score” for each person.

Any other scores like cost, if there is a lot of difference between group score and individual scorecan be considered as 'dissatisfaction score' for each person.



In [624]:
# Should you split in two groups today? 
print("Since the group's optimal restaurant choice of Mayuri is not in alignment with any individual's"
      "optimal restaurant choice, we should split into 2 groups.")

Since the group's optimal restaurant choice of Mayuri is not in alignment with any individual'soptimal restaurant choice, we should split into 2 groups.


In [625]:
# Ok. Now you just found out the boss is paying for the meal. How should you adjust. Now what is best restaurant?

people_dict_nocost =  {}
M_people_nocost = []

for key in people: 
    cat_dict = {}
    valueArray = np.random.dirichlet(np.ones(len(people_cat)),size=1)
    idx = 0
    for cat_key in people_cat: 
        if cat_key == 'cost':
            cat_dict[cat_key] = 0
        else:
            cat_dict[cat_key] = valueArray[0, idx] 
        idx += 1
    people_dict_nocost[key] = cat_dict
    M_people_nocost.append(valueArray[0])


In [629]:
M_people_nocost = np.array(M_people_nocost)

M_people_nocost_new = np.swapaxes(M_people_nocost, 0, 1)
M_usr_x_rest_nocost = np.matmul(M_restaurants, M_people_nocost_new)

Final_Restaurant_Scores_nocost = list(np.sum(M_usr_x_rest_nocost, axis=1))
max_Restaurant_Score_nocost = max(Final_Restaurant_Scores_nocost)
max_Restaurant_Score_nocost_index = Final_Restaurant_Scores_nocost.index(max_Restaurant_Score_nocost)

print(f"\nMax restaurant score is {max_Restaurant_Score_nocost}, which is {restaurants[max_Restaurant_Score_nocost_index]}.")



Max restaurant score is 41.33715173425514, which is Mayuri.


In [630]:
# Tommorow you visit another team. You have the same restaurants and they told you their optimal ordering for restaurants. 
# Can you find their weight matrix? 
print("We can get weight matrix by multiplying both restaurant matrix and transpose of the ordering matrix")

We can get weight matrix by multiplying both restaurant matrix and transpose of the ordering matrix
